### ISSUE TITLE
Integration not working after updating HA to 2021.9.4

### ISSUE THREAD

**Issue by jampez77** [ljmerza/ha-our-groceries#23]
## Version of the custom_component
1.3.9

## Configuration

```yaml
ourgroceries:
   username: !secret jamie_email
   password: !secret our_groceries_password

```

## Describe the bug
Intergration isnt working after updating the 2021.9.4

## Debug log

```text

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 255, in _async_setup_component
    result = await task
  File "/config/custom_components/ourgroceries/__init__.py", line 66, in async_setup
    await og.login()
  File "/usr/local/lib/python3.9/site-packages/ourgroceries/__init__.py", line 80, in login
    await self._get_team_id()
  File "/usr/local/lib/python3.9/site-packages/ourgroceries/__init__.py", line 110, in _get_team_id
    self._category_id = re.findall(REGEX_CATEGORY_ID, responseText)[0]
IndexError: list index out of range
```

**Comment by andreasbrett** [comment]
Same here

**Comment by 163Albert** [comment]
Ditto, same error message.

**Comment by nathan-curtis** [comment]
> Ditto, same error message.

Ditto the report - same error.  I was on 8.8 before upgrade.  Although, I've been on 9.2 at least a whole day or two (and very active in my install, im currently migrating from another system) and I don't remember the error popping immediately after my upgrade to 9.2.  It seemed 'new' to me tonight - thus why I came here to report it.

**Comment by rpitera** [comment]
Same issue and error message.  Best of my memory it started on 2021.9.3 for me.

**Comment by sevorl** [comment]
I can confirm, this does not work in 2021.9.5
I updated from 2021.8.x, so I don't know if this used to work in earlier versions of 2021.9.x

**Comment by papst01** [comment]
For ne it looks independent from the last HA updates. I only restarted Home Assistent and ourgroceries stopped working. I'm running core-2021.8.8. Error message is the same like the OP. So if the groceries component got no update then ourgroceries itself must have changed anything preventing the login.

**Comment by andreasbrett** [comment]
This is an issue with the login that changed on the server side of OurGroceries. See the used python libary and corresponding issue over there: https://github.com/ljmerza/py-our-groceries/issues/13

Once that is fixed, this HA integration will work again.

**Comment by rpitera** [comment]
Just want to keep this alive and stave off the stale bot.  :)

**Comment by davidwelsman** [comment]
OurGroceries Support advises (not unreasonable - though the word 'fishing' is dark)
"Home Assistant was fishing through our code to get information about lists. We can't keep our code unchanged forever, sometimes we want to make improvements. So there's nothing for us to "fix" here -- whoever wrote the Home Assistant code needs to update it, but also be aware that it'll keep breaking as long as they depend on undocumented parts of our code "

**Comment by andreasbrett** [comment]
Basic answer by a service provider that does not offer a public API and therefore third party code needs to scrape their web content. Unfortunately @ljmerza is not responding. The bug is fixed already and just needs to be merged.

**Comment by andreasbrett** [comment]
@ljmerza Thank you, that's good news. This is linked to https://github.com/ljmerza/py-our-groceries/issues/13 and https://github.com/ljmerza/py-our-groceries/pull/14

**Comment by rpitera** [comment]
> Sorry I never got the notification for this issue until someone tagged me. Will look at today

Good to know for the future! ; )  Thanks as always.

**Comment by ljmerza** [comment]
fixed in v1.3.10

**Comment by 163Albert** [comment]
Working well again. A huge thank you.

**Comment by andreasbrett** [comment]
@ljmerza could you please release 1.3.10? It's currently just a tag and latest_release still points to 1.3.9. HACS doesn't show an update to 1.3.10.

Thank you

Sep 27, 2021 06:29:37 163Albert ***@***.***>:

**Comment by rpitera** [comment]
>  could you please release 1.3.10? It's currently just a tag and latest_release still points to 1.3.9.

OK, so it's not just me...  I thought maybe there was an upstream dep that wasn't ready yet because I tried doing it manually and while the error went away, I didn't get a sensor.  Hopefully I just installed it wrong or something and HACS install will solve this.

**Comment by jampez77** [comment]
> could you please release 1.3.10? It's currently just a tag and latest_release still points to 1.3.9. HACS doesn't show an update to 1.3.10.

I second this as an issue! Still seeing 1.3.9 as the latest.

**Comment by davidwelsman** [comment]
As an interim measure I copied and  extracted the v1.3.10 zip file, and copied the contents of Our Groceries folder into the same named folder found in Config/Customer_Components.   It works....

**Comment by rpitera** [comment]
When I did that, the error notification went away, but I didn't get an our groceries sensor.   Been using HA since a few months after it's initial release, so I'm experienced with manual install method.  I figured that possibly the upstream library wasn't released yet, but apparently this isn't the case if it's working for you.  😕

**Comment by rpitera** [comment]
BTW, @ljmerza - I don't know why it didn't work for me when I installed it manually, but my HACS update solved my issues after a reboot.  Maybe I needed another reboot or two to get the dependency filled?  Anyways, I thought I would add that.  Thanks again!
